# thinkall/edge-computing:tfcpu1.11-py3.5
# build from ubuntu, python 3.5, tensorflow-cpu 1.11

# build from ubuntu, python 3.6, tensorflow-cpu 1.9

#from arm64v8/ubuntu:16.04
#16.04 pip3 install raise errors

from arm64v8/ubuntu:18.04

MAINTAINER Li JIANG <bnujli@gmail.com>

# Install systems libs
RUN apt-get update && \
    apt-get install -y \
    apt-utils curl libcurl3-dev libfreetype6-dev libglu1-mesa libglu1-mesa-dev \
    libhdf5-dev hdf5-tools libhdf5-serial-dev libjpeg8-dev libpng-dev libtool \
    libx11-dev libxi-dev libxmu-dev libzmq3-dev openjdk-8-jdk \
    openjdk-8-jre-headless python3 python3-dev python3-pip vim wget curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install python packages
RUN HDF5_DIR=/usr/lib/aarch64-linux-gnu/hdf5/serial/  \
    pip3 install --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple  --no-cache-dir \
    astor future>=0.17.1 gast google-pasta \
    grpcio h5py keras-applications keras-preprocessing mock numpy \
    requests six wrapt flask json5 Pillow matplotlib celery redis

# Install tensorflow
#RUN pip3 install --no-cache-dir https://raw.githubusercontent.com/dujiangsu/tensorflow-1.11.0-cp35-cp35m-linux_aarch64/master/tensorflow-1.11.0-cp35-cp35m-linux_aarch64.whl

RUN pip3 install --no-cache-dir https://raw.githubusercontent.com/markjay4k/Tensorflow-1.9rc0-py36-aarch64/master/tensorflow-1.9.0rc0-cp36-cp36m-linux_aarch64.whl


WORKDIR /workspace/

COPY . .

WORKDIR code/


ENTRYPOINT python3 im2txt_stream.py


